% This functions maps every transition to its corresponding output place.
function [return_dict] = transition_place_map()

transitions = ["tCateriumOreMiner",'tIronOreMiner','tCopperOreMiner','tCoalMiner','tLimestoneMiner','tBauxiteMiner','tRawQuartzMiner','tSulfurMiner','tCrudeOilExtractor','tWaterExtractor','tNitrogenGasResourceWellExtractor'...
              'tSmelterForCaterium','tSmelterForIron','tSmelterForCopper',...
              'tFoundryForSteelIngot','tFoundryForAluminumIngot',...
              'tConstructorForIronPlate','tConstructorForIronRod','tConstructorForScrew','tConstructorForCopperSheet','tConstructorForWire','tConstructorForCopperPowder','tConstructorForQuickwire','tConstructorForSilica',...
              'tConstructorForSteelPipe','tConstructorForSteelBeam','tConstructorForConcrete','tConstructorForCable','tConstructorForQuartzCrystal','tConstructorForAluminumCasing',...
              'tRefineryForPlasticAndHeavyOilResidue','tRefineryForRubberAndHeavyOilResidue','tRefineryForAluminaSolutionAndSilica','tRefineryForAluminumScrapAndWater','tRefineryForSulfuricAcid',...
              'tAssemblerForReinforcedIronPlate','tAssemblerForStator','tAssemblerForRotor','tAssemblerForMotor','tAssemblerForSmartPlating','tAssemblerForModularFrame','tAssemblerForCircuitBoard',...
              'tAssemblerForAlcladAluminumSheet','tAssemblerForAutomatedWiring','tAssemblerForVersatileFramework','tAssemblerForEncasedIndustrialBeam','tAssemblerAILimiter','tAssemblerForHeatSink',...
              'tAssemblerForPressureConversionCube','tAssemblerForElectromagneticControlRod','tAssemblerForAssemblyDirectorSystem',...
              'tBlenderForCoolingSystem','tBlenderForFusedModularFrame','tBlenderForBatteryAndWater',...
              'tManufacturerForHeavyModularFrame','tManufacturerForComputer','tManufacturerForHighSpeedConnector','tManufacturerForSupercomputer','tManufacturerForAdaptiveControlUnit','tManufacturerForCrystalOscillator',...
              'tManufacturerForRadioControlUnit','tManufacturerForModularEngine','tManufacturerForTurboMotor','tManufacturerForThermalPropulsionRocket','tManufacturerForMagneticFieldGenerator',...
              'tParticleAcceleratorForNuclearPasta'];

places = ["pCateriumOre",'pIronOre','pCopperOre','pCoal','pLimestone','pBauxite','pRawQuartz','pSulfur','pCrudeOil','pWater','pNitrogenGas',...
          'pCateriumIngot','pIronIngot','pCopperIngot',...
          'pSteelIngot','pAluminumIngot',...
          'pIronPlate','pIronRod','pScrew','pCopperSheet','pWire','pCopperPowder','pQuickwire','pSilica',...
          'pSteelPipe','pSteelBeam','pConcrete','pCable','pQuartzCrystal','pAluminumCasing',...
          'pPlastic','pRubber','pAluminaSolution','pAluminumScrap','pSulfuricAcid',...
          'pReinforcedIronPlate','pStator','pRotor','pMotor','pSmartPlating','pModularFrame','pCircuitBoard',...
          'pAlcladAluminumSheet','pAutomatedWiring','pVersatileFramework','pEncasedIndustrialBeam','pAILimiter','pHeatSink',...
          'pPressureConversionCube','pElectromagneticControlRod','pAssemblyDirectorSystem',...
          'pCoolingSystem','pFusedModularFrame','pBattery',...
          'pHeavyModularFrame','pComputer','pHighSpeedConnector','pSupercomputer','pAdaptiveControlUnit','pCrystalOscillator',...
          'pRadioControlUnit','pModularEngine','pTurboMotor','pThermalPropulsionRocket','pMagneticFieldGenerator',...
          'pNuclearPasta'
          ];

return_dict = dictionary(transitions, places);