function [return_dict] = transition_output_rates()

global global_info

transitions = [
    "tIronOreMiner",'tCopperOreMiner','tCoalMiner',...
    'tSmelterForIron','tSmelterForCopper','tFoundryForSteelIngot',...
    'tConstructorForIronPlate','tConstructorForIronRod','tConstructorForScrew','tConstructorForWire',...
    'tConstructorForSteelPipe','tConstructorForSteelBeam','tConstructorForCable',...
    'tAssemblerForReinforcedIronPlate','tAssemblerForStator','tAssemblerForRotor','tAssemblerForModularFrame',...
    'tAssemblerForAutomatedWiring','tAssemblerForVersatileFramework','tAssemblerForSmartPlating'
]; 


transition_rates = [
    30 * 2 ^(global_info.Miner_Tier - 1) * 2 ^(global_info.Node_Purity - 1) * global_info.Counters("tIronOreMiner"),...
    30 * 2 ^(global_info.Miner_Tier - 1) * 2 ^(global_info.Node_Purity - 1) * global_info.Counters("tCopperOreMiner"),...
    30 * 2 ^(global_info.Miner_Tier - 1) * 2 ^(global_info.Node_Purity - 1) * global_info.Counters("tCoalMiner"),...
    30 *  global_info.Counters("tSmelterForIron"),...
    30 *  global_info.Counters("tSmelterForCopper"),...
    45 *  global_info.Counters("tFoundryForSteelIngot"),...
    20 *  global_info.Counters("tConstructorForIronPlate"),...
    15 *  global_info.Counters("tConstructorForIronRod"),...
    40 *  global_info.Counters("tConstructorForScrew"),...
    30 *  global_info.Counters("tConstructorForWire"),...
    20 *  global_info.Counters("tConstructorForSteelPipe"),...
    15 *  global_info.Counters("tConstructorForSteelBeam"),...
    30 *  global_info.Counters("tConstructorForCable"),...
    5 *   global_info.Counters("tAssemblerForReinforcedIronPlate"),...
    5 *   global_info.Counters("tAssemblerForStator"),...
    4 *   global_info.Counters("tAssemblerForRotor"),...
    2 *   global_info.Counters("tAssemblerForModularFrame"),...
    5 *   global_info.Counters("tAssemblerForAutomatedWiring"),...
    10 *  global_info.Counters("tAssemblerForVersatileFramework"),...
    2 *   global_info.Counters("tAssemblerForSmartPlating")
];

return_dict = dictionary(transitions, transition_rates);